baseURL = 'https://roadnotfixed.github.io/'
locale = 'en-US'
title = 'Narrenschiff'
theme = 'hugo-bearblog'
enableRobotsTXT = true

[[menus.main]]
  name = 'Blog'
  pageRef = '/blog'
  weight = 10

[[menus.main]]
  name = 'Photo'
  pageRef = '/photos'
  weight = 15

[[menus.main]]
  name = 'Running'
  pageRef = '/running'
  weight = 20

[[menus.main]]
  name = 'Timeline'
  pageRef = '/timeline'
  weight = 25

[[menus.main]]
  name = 'Links'
  pageRef = '/links'
  weight = 40

[params]
  description = 'Narrenschiff'
  favicon = 'images/favicon.png'
  images = ['images/share.png']
  title = 'Narrenschiff'
