baseURL = 'https://roadnotfixed.github.io/'
languageCode = 'en-us'
title = 'Narrenschiff'
theme = 'hugo-bearblog'
enableRobotsTXT = true

[params]
  description = 'Narrenschiff'
  favicon = 'images/favicon.png'
  images = ['images/share.png']
  title = 'Narrenschiff'
